### ISSUE TITLE
Error: Package runspired/hammer.js=runspired/hammer.js not found

### ISSUE THREAD

**Issue by RuslanZavacky** [runspired/ember-gestures#2]
Trying to install gestures via `ember install ember-gestures` and getting this error:

```
ember install ember-gestures
version: 1.13.8
Installed packages for tooling via npm.
installing ember-gestures
Installing browser packages via Bower...
  cached git://github.com/hammerjs/hammer-time.git#0.2.2
Package runspired/hammer.js=runspired/hammer.js not found
Error: Package runspired/hammer.js=runspired/hammer.js not found
    at createError (/ui/node_modules/ember-cli/node_modules/bower/lib/util/createError.js:4:15)
    at /ui/node_modules/ember-cli/node_modules/bower/lib/core/resolverFactory.js:143:27
    at _fulfilled (/ui/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/ui/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/ui/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:796:13)
    at /ui/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:604:44
    at runSingle (/ui/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:137:13)
    at flush (/ui/node_modules/ember-cli/node_modules/bower/node_modules/q/q.js:125:13)
    at process._tickCallback (node.js:355:11)
```

**Comment by runspired** [comment]
Apparently (from what I can tell) ember-cli does not like to install bower packages in this manner unless they are locally available.  `bower install --save runspired/hammer.js#develop` should do the trick.

**Comment by runspired** [comment]
Also note, this is temporary, we're releasing Hammer 2.0.5 soon, and minus a few more bug fixes etc. this branch is what will be Hammer 2.0.5

**Comment by RuslanZavacky** [comment]
@runspired yeap, I've managed to install it. I just want to test it, won't be in production :)

**Comment by runspired** [comment]
Awesome. Ping me on slack there aren't exactly docs yet but there are some interesting gems here.

**Comment by JKGisMe** [comment]
+1 for this error

**Comment by runspired** [comment]
See newest release

**Comment by JKGisMe** [comment]
Wouldn't `ember install ember-gestures` give me the newest release?

**Comment by JKGisMe** [comment]
Haha not if it was only 6 mins ago I guess!

**Comment by runspired** [comment]
You missed it by a few minutes
