### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by erichonkanen** [runspired/ember-gestures#55]
```
ember install ember-gestures
Installed packages for tooling via npm.
Cannot find module 'ember-cli-version-checker'
Error: Cannot find module 'ember-cli-version-checker'
```

**Comment by erichonkanen** [comment]
worked 2nd time

**Comment by sir-dunxalot** [comment]
I am having this issue but it's not resolving itself on multiple installs:

```
Cannot find module 'ember-cli-version-checker'
Error: Cannot find module 'ember-cli-version-checker'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Duncan/Development/test-app/node_modules/ember-gestures/blueprints/ember-gestures/index.js:1:84)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by sir-dunxalot** [comment]
I had to run `npm install --save-dev ember-cli-version-checker` before `ember install ember-gestures` to get the installation of this addon to succeed.
