### ISSUE TITLE
Cannot find module 'ember-cli-version-checker'

### ISSUE THREAD

**Issue by quangv** [runspired/ember-gestures#62]
I get this error on `ember install ember-gestures`

```
$ ember install ember-gestures
Installed packages for tooling via npm.
Cannot find module 'ember-cli-version-checker'
Error: Cannot find module 'ember-cli-version-checker'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/quang/dev/org/client/node_modules/ember-gestures/blueprints/ember-gestures/index.js:1:84)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

```
ember-cli: 2.6.3
node: 4.4.7
os: linux x64
```

**Comment by quangv** [comment]
seems like not alone #55

**Comment by devinrhode2** [comment]
I think just doing `npm install ember-cli-version-checker --save-dev` works around this issue.

**Comment by 0000marcell** [comment]
@devinrhode2 yes it works,  i had to reinstall everything but it works.
